package com.edaixi.activity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.edaixi.activity.OpenCityModle;

import com.edaixi.activity.OpenCityModleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig openCityModleDaoConfig;

    private final OpenCityModleDao openCityModleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        openCityModleDaoConfig = daoConfigMap.get(OpenCityModleDao.class).clone();
        openCityModleDaoConfig.initIdentityScope(type);

        openCityModleDao = new OpenCityModleDao(openCityModleDaoConfig, this);

        registerDao(OpenCityModle.class, openCityModleDao);
    }
    
    public void clear() {
        openCityModleDaoConfig.getIdentityScope().clear();
    }

    public OpenCityModleDao getOpenCityModleDao() {
        return openCityModleDao;
    }

}
