package com.edaixi.activity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OPEN_CITY_MODLE.
 */
public class OpenCityModle {

	private long id;
	private String name;
	private Boolean is_show;
	private String created_at;
	private String updated_at;
	private String fuwufanwei;
	private String initials;

	public OpenCityModle() {
	}

	public OpenCityModle(long id) {
		this.id = id;
	}

	public OpenCityModle(long id, String name, Boolean is_show,
			String created_at, String updated_at, String fuwufanwei,
			String initials) {
		this.id = id;
		this.name = name;
		this.is_show = is_show;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.fuwufanwei = fuwufanwei;
		this.initials = initials;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getIs_show() {
		return is_show;
	}

	public void setIs_show(Boolean is_show) {
		this.is_show = is_show;
	}

	public String getCreated_at() {
		return created_at;
	}

	public void setCreated_at(String created_at) {
		this.created_at = created_at;
	}

	public String getUpdated_at() {
		return updated_at;
	}

	public void setUpdated_at(String updated_at) {
		this.updated_at = updated_at;
	}

	public String getFuwufanwei() {
		return fuwufanwei;
	}

	public void setFuwufanwei(String fuwufanwei) {
		this.fuwufanwei = fuwufanwei;
	}

	public String getInitials() {
		return initials;
	}

	public void setInitials(String initials) {
		this.initials = initials;
	}

	@Override
	public String toString() {
		return "OpenCityModle [id=" + id + ", name=" + name + ", is_show="
				+ is_show + ", created_at=" + created_at + ", updated_at="
				+ updated_at + ", fuwufanwei=" + fuwufanwei + ", initials="
				+ initials + "]";
	}

}
